extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  document-start: disable
  document-end: disable

ignore: |
  node_modules/
  .expo/
  dist/
  build/
  coverage/
